import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tg-bg':                '#f0f2f5',
        'tg-bg-dark':           '#0f1923',
        'tg-surface':           '#ffffff',
        'tg-surface-dark':      '#17212b',
        'tg-raised':            '#f8f9fa',
        'tg-raised-dark':       '#1c2733',
        'tg-active':            '#e8f4fd',
        'tg-active-dark':       '#1e3a5f',
        'tg-reply':             '#f0f7ff',
        'tg-reply-dark':        '#1a2840',
        'tg-badge-bg':          '#f0f0f0',
        'tg-badge-bg-dark':     '#2a3547',
        'tg-input':             '#ffffff',
        'tg-input-dark':        '#1c2733',
        'tg-nav':               '#1c2733',
        'tg-nav-dark':          '#0d1117',
        'tg-highlight':         '#e3f2fd',
        'tg-highlight-dark':    '#1e3a5f',
        'tg-border':            '#e5e5e5',
        'tg-border-dark':       '#2a3a4a',
        'tg-border-light':      '#f0f0f0',
        'tg-border-light-dark': '#1e2e3e',
        'tg-border-input':      '#dddddd',
        'tg-border-input-dark': '#3a4a5a',
        'tg-text':              '#222222',
        'tg-text-dark':         '#e8eaed',
        'tg-text-sub':          '#888888',
        'tg-text-sub-dark':     '#8899aa',
        'tg-text-muted':        '#aaaaaa',
        'tg-text-muted-dark':   '#6c737a',
        'tg-text-badge':        '#666666',
        'tg-text-badge-dark':   '#8899aa',
        'tg-blue':              '#2AABEE',
      },
      boxShadow: {
        card:      '0 4px 24px rgba(0,0,0,0.08)',
        'card-dark': '0 4px 24px rgba(0,0,0,0.4)',
        overlay:   '0 8px 32px rgba(0,0,0,0.18)',
      },
    },
  },
  plugins: [],
} satisfies Config;
